language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brktopcu/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true brktopcu/docker-react-example npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-example"
  env: "DockerReactExample-env"
  bucket_name: "elasticbeanstalk-us-east-2-926265719947"
  bucket_path: "docker-react-example"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
