language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brktopcu/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true brktopcu/docker-react-example npm run test
